name: main.linux.py312

on:
  push:
    branches: [ develop, feature/*, release/* ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Show Python version
        run: python --version
      - name: Setup hatch
        run: python -m pip install --upgrade hatch
      - name: Build
        run: ./make.sh
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
